# Generated by Django 5.0.14 on 2026-06-26 09:37

import agent.models
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[agent.models.validate_video_size], verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
