# Generated by Django 5.0.14 on 2026-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_property_video_alter_property_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title_document',
            field=models.CharField(choices=[('C of O', 'C of O'), ('R of O', 'R of O'), ('Deed of Assignment', 'Deed of Assignment'), ('Survey Plan', 'Survey Plan'), ('Governor Consent', 'Governor Consent'), ('Gazette', 'Gazette'), ('Excision', 'Excision'), ('Freehold', 'Freehold')], max_length=64),
        ),
    ]
